// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/message.proto

package com.bfxy.common.protobuf;

public final class MessageModule {
  private MessageModule() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code MessageType}
   */
  public enum MessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>REQUEST = 0;</code>
     */
    REQUEST(0),
    /**
     * <code>RESPONSE = 1;</code>
     */
    RESPONSE(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>REQUEST = 0;</code>
     */
    public static final int REQUEST_VALUE = 0;
    /**
     * <code>RESPONSE = 1;</code>
     */
    public static final int RESPONSE_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageType valueOf(int value) {
      return forNumber(value);
    }

    public static MessageType forNumber(int value) {
      switch (value) {
        case 0: return REQUEST;
        case 1: return RESPONSE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MessageType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            public MessageType findValueByNumber(int number) {
              return MessageType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.bfxy.common.protobuf.MessageModule.getDescriptor().getEnumTypes().get(0);
    }

    private static final MessageType[] VALUES = values();

    public static MessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MessageType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:MessageType)
  }

  /**
   * Protobuf enum {@code ResultType}
   */
  public enum ResultType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SUCCESS = 0;</code>
     */
    SUCCESS(0),
    /**
     * <code>FAILURE = 1;</code>
     */
    FAILURE(1),
    /**
     * <code>SYS_ERROR = 2;</code>
     */
    SYS_ERROR(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>SUCCESS = 0;</code>
     */
    public static final int SUCCESS_VALUE = 0;
    /**
     * <code>FAILURE = 1;</code>
     */
    public static final int FAILURE_VALUE = 1;
    /**
     * <code>SYS_ERROR = 2;</code>
     */
    public static final int SYS_ERROR_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ResultType valueOf(int value) {
      return forNumber(value);
    }

    public static ResultType forNumber(int value) {
      switch (value) {
        case 0: return SUCCESS;
        case 1: return FAILURE;
        case 2: return SYS_ERROR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ResultType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ResultType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ResultType>() {
            public ResultType findValueByNumber(int number) {
              return ResultType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.bfxy.common.protobuf.MessageModule.getDescriptor().getEnumTypes().get(1);
    }

    private static final ResultType[] VALUES = values();

    public static ResultType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ResultType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ResultType)
  }

  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 crcCode = 1;</code>
     */
    long getCrcCode();

    /**
     * <code>.MessageType messageType = 2;</code>
     */
    int getMessageTypeValue();
    /**
     * <code>.MessageType messageType = 2;</code>
     */
    com.bfxy.common.protobuf.MessageModule.MessageType getMessageType();

    /**
     * <code>.ResultType resultType = 3;</code>
     */
    int getResultTypeValue();
    /**
     * <code>.ResultType resultType = 3;</code>
     */
    com.bfxy.common.protobuf.MessageModule.ResultType getResultType();

    /**
     * <code>string module = 4;</code>
     */
    java.lang.String getModule();
    /**
     * <code>string module = 4;</code>
     */
    com.google.protobuf.ByteString
        getModuleBytes();

    /**
     * <code>string cmd = 5;</code>
     */
    java.lang.String getCmd();
    /**
     * <code>string cmd = 5;</code>
     */
    com.google.protobuf.ByteString
        getCmdBytes();

    /**
     * <code>bytes body = 6;</code>
     */
    com.google.protobuf.ByteString getBody();
  }
  /**
   * Protobuf type {@code Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      messageType_ = 0;
      resultType_ = 0;
      module_ = "";
      cmd_ = "";
      body_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              crcCode_ = input.readInt64();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              messageType_ = rawValue;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              resultType_ = rawValue;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              module_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              cmd_ = s;
              break;
            }
            case 50: {

              body_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bfxy.common.protobuf.MessageModule.internal_static_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bfxy.common.protobuf.MessageModule.internal_static_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bfxy.common.protobuf.MessageModule.Message.class, com.bfxy.common.protobuf.MessageModule.Message.Builder.class);
    }

    public static final int CRCCODE_FIELD_NUMBER = 1;
    private long crcCode_;
    /**
     * <code>int64 crcCode = 1;</code>
     */
    public long getCrcCode() {
      return crcCode_;
    }

    public static final int MESSAGETYPE_FIELD_NUMBER = 2;
    private int messageType_;
    /**
     * <code>.MessageType messageType = 2;</code>
     */
    public int getMessageTypeValue() {
      return messageType_;
    }
    /**
     * <code>.MessageType messageType = 2;</code>
     */
    public com.bfxy.common.protobuf.MessageModule.MessageType getMessageType() {
      @SuppressWarnings("deprecation")
      com.bfxy.common.protobuf.MessageModule.MessageType result = com.bfxy.common.protobuf.MessageModule.MessageType.valueOf(messageType_);
      return result == null ? com.bfxy.common.protobuf.MessageModule.MessageType.UNRECOGNIZED : result;
    }

    public static final int RESULTTYPE_FIELD_NUMBER = 3;
    private int resultType_;
    /**
     * <code>.ResultType resultType = 3;</code>
     */
    public int getResultTypeValue() {
      return resultType_;
    }
    /**
     * <code>.ResultType resultType = 3;</code>
     */
    public com.bfxy.common.protobuf.MessageModule.ResultType getResultType() {
      @SuppressWarnings("deprecation")
      com.bfxy.common.protobuf.MessageModule.ResultType result = com.bfxy.common.protobuf.MessageModule.ResultType.valueOf(resultType_);
      return result == null ? com.bfxy.common.protobuf.MessageModule.ResultType.UNRECOGNIZED : result;
    }

    public static final int MODULE_FIELD_NUMBER = 4;
    private volatile java.lang.Object module_;
    /**
     * <code>string module = 4;</code>
     */
    public java.lang.String getModule() {
      java.lang.Object ref = module_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        module_ = s;
        return s;
      }
    }
    /**
     * <code>string module = 4;</code>
     */
    public com.google.protobuf.ByteString
        getModuleBytes() {
      java.lang.Object ref = module_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        module_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CMD_FIELD_NUMBER = 5;
    private volatile java.lang.Object cmd_;
    /**
     * <code>string cmd = 5;</code>
     */
    public java.lang.String getCmd() {
      java.lang.Object ref = cmd_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cmd_ = s;
        return s;
      }
    }
    /**
     * <code>string cmd = 5;</code>
     */
    public com.google.protobuf.ByteString
        getCmdBytes() {
      java.lang.Object ref = cmd_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cmd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BODY_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString body_;
    /**
     * <code>bytes body = 6;</code>
     */
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (crcCode_ != 0L) {
        output.writeInt64(1, crcCode_);
      }
      if (messageType_ != com.bfxy.common.protobuf.MessageModule.MessageType.REQUEST.getNumber()) {
        output.writeEnum(2, messageType_);
      }
      if (resultType_ != com.bfxy.common.protobuf.MessageModule.ResultType.SUCCESS.getNumber()) {
        output.writeEnum(3, resultType_);
      }
      if (!getModuleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, module_);
      }
      if (!getCmdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, cmd_);
      }
      if (!body_.isEmpty()) {
        output.writeBytes(6, body_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (crcCode_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, crcCode_);
      }
      if (messageType_ != com.bfxy.common.protobuf.MessageModule.MessageType.REQUEST.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, messageType_);
      }
      if (resultType_ != com.bfxy.common.protobuf.MessageModule.ResultType.SUCCESS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, resultType_);
      }
      if (!getModuleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, module_);
      }
      if (!getCmdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, cmd_);
      }
      if (!body_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, body_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bfxy.common.protobuf.MessageModule.Message)) {
        return super.equals(obj);
      }
      com.bfxy.common.protobuf.MessageModule.Message other = (com.bfxy.common.protobuf.MessageModule.Message) obj;

      if (getCrcCode()
          != other.getCrcCode()) return false;
      if (messageType_ != other.messageType_) return false;
      if (resultType_ != other.resultType_) return false;
      if (!getModule()
          .equals(other.getModule())) return false;
      if (!getCmd()
          .equals(other.getCmd())) return false;
      if (!getBody()
          .equals(other.getBody())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CRCCODE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCrcCode());
      hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
      hash = (53 * hash) + messageType_;
      hash = (37 * hash) + RESULTTYPE_FIELD_NUMBER;
      hash = (53 * hash) + resultType_;
      hash = (37 * hash) + MODULE_FIELD_NUMBER;
      hash = (53 * hash) + getModule().hashCode();
      hash = (37 * hash) + CMD_FIELD_NUMBER;
      hash = (53 * hash) + getCmd().hashCode();
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bfxy.common.protobuf.MessageModule.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bfxy.common.protobuf.MessageModule.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bfxy.common.protobuf.MessageModule.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bfxy.common.protobuf.MessageModule.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bfxy.common.protobuf.MessageModule.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bfxy.common.protobuf.MessageModule.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bfxy.common.protobuf.MessageModule.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bfxy.common.protobuf.MessageModule.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bfxy.common.protobuf.MessageModule.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bfxy.common.protobuf.MessageModule.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bfxy.common.protobuf.MessageModule.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bfxy.common.protobuf.MessageModule.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bfxy.common.protobuf.MessageModule.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Message)
        com.bfxy.common.protobuf.MessageModule.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bfxy.common.protobuf.MessageModule.internal_static_Message_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bfxy.common.protobuf.MessageModule.internal_static_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bfxy.common.protobuf.MessageModule.Message.class, com.bfxy.common.protobuf.MessageModule.Message.Builder.class);
      }

      // Construct using com.bfxy.common.protobuf.MessageModule.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        crcCode_ = 0L;

        messageType_ = 0;

        resultType_ = 0;

        module_ = "";

        cmd_ = "";

        body_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bfxy.common.protobuf.MessageModule.internal_static_Message_descriptor;
      }

      @java.lang.Override
      public com.bfxy.common.protobuf.MessageModule.Message getDefaultInstanceForType() {
        return com.bfxy.common.protobuf.MessageModule.Message.getDefaultInstance();
      }

      @java.lang.Override
      public com.bfxy.common.protobuf.MessageModule.Message build() {
        com.bfxy.common.protobuf.MessageModule.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.bfxy.common.protobuf.MessageModule.Message buildPartial() {
        com.bfxy.common.protobuf.MessageModule.Message result = new com.bfxy.common.protobuf.MessageModule.Message(this);
        result.crcCode_ = crcCode_;
        result.messageType_ = messageType_;
        result.resultType_ = resultType_;
        result.module_ = module_;
        result.cmd_ = cmd_;
        result.body_ = body_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bfxy.common.protobuf.MessageModule.Message) {
          return mergeFrom((com.bfxy.common.protobuf.MessageModule.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bfxy.common.protobuf.MessageModule.Message other) {
        if (other == com.bfxy.common.protobuf.MessageModule.Message.getDefaultInstance()) return this;
        if (other.getCrcCode() != 0L) {
          setCrcCode(other.getCrcCode());
        }
        if (other.messageType_ != 0) {
          setMessageTypeValue(other.getMessageTypeValue());
        }
        if (other.resultType_ != 0) {
          setResultTypeValue(other.getResultTypeValue());
        }
        if (!other.getModule().isEmpty()) {
          module_ = other.module_;
          onChanged();
        }
        if (!other.getCmd().isEmpty()) {
          cmd_ = other.cmd_;
          onChanged();
        }
        if (other.getBody() != com.google.protobuf.ByteString.EMPTY) {
          setBody(other.getBody());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bfxy.common.protobuf.MessageModule.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bfxy.common.protobuf.MessageModule.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long crcCode_ ;
      /**
       * <code>int64 crcCode = 1;</code>
       */
      public long getCrcCode() {
        return crcCode_;
      }
      /**
       * <code>int64 crcCode = 1;</code>
       */
      public Builder setCrcCode(long value) {
        
        crcCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 crcCode = 1;</code>
       */
      public Builder clearCrcCode() {
        
        crcCode_ = 0L;
        onChanged();
        return this;
      }

      private int messageType_ = 0;
      /**
       * <code>.MessageType messageType = 2;</code>
       */
      public int getMessageTypeValue() {
        return messageType_;
      }
      /**
       * <code>.MessageType messageType = 2;</code>
       */
      public Builder setMessageTypeValue(int value) {
        messageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.MessageType messageType = 2;</code>
       */
      public com.bfxy.common.protobuf.MessageModule.MessageType getMessageType() {
        @SuppressWarnings("deprecation")
        com.bfxy.common.protobuf.MessageModule.MessageType result = com.bfxy.common.protobuf.MessageModule.MessageType.valueOf(messageType_);
        return result == null ? com.bfxy.common.protobuf.MessageModule.MessageType.UNRECOGNIZED : result;
      }
      /**
       * <code>.MessageType messageType = 2;</code>
       */
      public Builder setMessageType(com.bfxy.common.protobuf.MessageModule.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        messageType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.MessageType messageType = 2;</code>
       */
      public Builder clearMessageType() {
        
        messageType_ = 0;
        onChanged();
        return this;
      }

      private int resultType_ = 0;
      /**
       * <code>.ResultType resultType = 3;</code>
       */
      public int getResultTypeValue() {
        return resultType_;
      }
      /**
       * <code>.ResultType resultType = 3;</code>
       */
      public Builder setResultTypeValue(int value) {
        resultType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.ResultType resultType = 3;</code>
       */
      public com.bfxy.common.protobuf.MessageModule.ResultType getResultType() {
        @SuppressWarnings("deprecation")
        com.bfxy.common.protobuf.MessageModule.ResultType result = com.bfxy.common.protobuf.MessageModule.ResultType.valueOf(resultType_);
        return result == null ? com.bfxy.common.protobuf.MessageModule.ResultType.UNRECOGNIZED : result;
      }
      /**
       * <code>.ResultType resultType = 3;</code>
       */
      public Builder setResultType(com.bfxy.common.protobuf.MessageModule.ResultType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        resultType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.ResultType resultType = 3;</code>
       */
      public Builder clearResultType() {
        
        resultType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object module_ = "";
      /**
       * <code>string module = 4;</code>
       */
      public java.lang.String getModule() {
        java.lang.Object ref = module_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          module_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string module = 4;</code>
       */
      public com.google.protobuf.ByteString
          getModuleBytes() {
        java.lang.Object ref = module_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          module_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string module = 4;</code>
       */
      public Builder setModule(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        module_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string module = 4;</code>
       */
      public Builder clearModule() {
        
        module_ = getDefaultInstance().getModule();
        onChanged();
        return this;
      }
      /**
       * <code>string module = 4;</code>
       */
      public Builder setModuleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        module_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object cmd_ = "";
      /**
       * <code>string cmd = 5;</code>
       */
      public java.lang.String getCmd() {
        java.lang.Object ref = cmd_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cmd_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string cmd = 5;</code>
       */
      public com.google.protobuf.ByteString
          getCmdBytes() {
        java.lang.Object ref = cmd_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cmd_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cmd = 5;</code>
       */
      public Builder setCmd(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string cmd = 5;</code>
       */
      public Builder clearCmd() {
        
        cmd_ = getDefaultInstance().getCmd();
        onChanged();
        return this;
      }
      /**
       * <code>string cmd = 5;</code>
       */
      public Builder setCmdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cmd_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes body = 6;</code>
       */
      public com.google.protobuf.ByteString getBody() {
        return body_;
      }
      /**
       * <code>bytes body = 6;</code>
       */
      public Builder setBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes body = 6;</code>
       */
      public Builder clearBody() {
        
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Message)
    }

    // @@protoc_insertion_point(class_scope:Message)
    private static final com.bfxy.common.protobuf.MessageModule.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bfxy.common.protobuf.MessageModule.Message();
    }

    public static com.bfxy.common.protobuf.MessageModule.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @java.lang.Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.bfxy.common.protobuf.MessageModule.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023proto/message.proto\"\211\001\n\007Message\022\017\n\007crc" +
      "Code\030\001 \001(\003\022!\n\013messageType\030\002 \001(\0162\014.Messag" +
      "eType\022\037\n\nresultType\030\003 \001(\0162\013.ResultType\022\016" +
      "\n\006module\030\004 \001(\t\022\013\n\003cmd\030\005 \001(\t\022\014\n\004body\030\006 \001(" +
      "\014*(\n\013MessageType\022\013\n\007REQUEST\020\000\022\014\n\010RESPONS" +
      "E\020\001*5\n\nResultType\022\013\n\007SUCCESS\020\000\022\013\n\007FAILUR" +
      "E\020\001\022\r\n\tSYS_ERROR\020\002B)\n\030com.bfxy.common.pr" +
      "otobufB\rMessageModuleb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_descriptor,
        new java.lang.String[] { "CrcCode", "MessageType", "ResultType", "Module", "Cmd", "Body", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
