package com.example.tccdemo.db131.model;

import java.math.BigDecimal;

public class AccountA {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_a.id
     *
     * @mbg.generated Thu Oct 03 14:32:45 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_a.name
     *
     * @mbg.generated Thu Oct 03 14:32:45 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_a.balance
     *
     * @mbg.generated Thu Oct 03 14:32:45 CST 2019
     */
    private BigDecimal balance;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_a.id
     *
     * @return the value of account_a.id
     *
     * @mbg.generated Thu Oct 03 14:32:45 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_a.id
     *
     * @param id the value for account_a.id
     *
     * @mbg.generated Thu Oct 03 14:32:45 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_a.name
     *
     * @return the value of account_a.name
     *
     * @mbg.generated Thu Oct 03 14:32:45 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_a.name
     *
     * @param name the value for account_a.name
     *
     * @mbg.generated Thu Oct 03 14:32:45 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_a.balance
     *
     * @return the value of account_a.balance
     *
     * @mbg.generated Thu Oct 03 14:32:45 CST 2019
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_a.balance
     *
     * @param balance the value for account_a.balance
     *
     * @mbg.generated Thu Oct 03 14:32:45 CST 2019
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }
}