package com.example.shardingjdbcdemo.dao;

import com.example.shardingjdbcdemo.model.OrderItem;
import com.example.shardingjdbcdemo.model.OrderItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_1
     *
     * @mbg.generated Sat Sep 21 23:10:26 CST 2019
     */
    long countByExample(OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_1
     *
     * @mbg.generated Sat Sep 21 23:10:26 CST 2019
     */
    int deleteByExample(OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_1
     *
     * @mbg.generated Sat Sep 21 23:10:26 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_1
     *
     * @mbg.generated Sat Sep 21 23:10:26 CST 2019
     */
    int insert(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_1
     *
     * @mbg.generated Sat Sep 21 23:10:26 CST 2019
     */
    int insertSelective(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_1
     *
     * @mbg.generated Sat Sep 21 23:10:26 CST 2019
     */
    List<OrderItem> selectByExample(OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_1
     *
     * @mbg.generated Sat Sep 21 23:10:26 CST 2019
     */
    OrderItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_1
     *
     * @mbg.generated Sat Sep 21 23:10:26 CST 2019
     */
    int updateByExampleSelective(@Param("record") OrderItem record, @Param("example") OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_1
     *
     * @mbg.generated Sat Sep 21 23:10:26 CST 2019
     */
    int updateByExample(@Param("record") OrderItem record, @Param("example") OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_1
     *
     * @mbg.generated Sat Sep 21 23:10:26 CST 2019
     */
    int updateByPrimaryKeySelective(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item_1
     *
     * @mbg.generated Sat Sep 21 23:10:26 CST 2019
     */
    int updateByPrimaryKey(OrderItem record);
}